---
title: "Impact Of Covid-19 On A&E's In Scotland"
author: "The A-Team <br> Alice Bullard, Alice Miller, Annie O'Dell, Anna Scollay"
institute: "University of Edinburgh"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader: 
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: false
      countIncrementalSlides: false
      
---

```{r load-packages, include = FALSE}
library(tidyverse)
library(tidymodels)
library(palmerpenguins)
library(knitr)
library(xaringanthemer)
library(maps)
library(gridExtra)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.retina = 3, dpi = 300, fig.width = 6, fig.asp = 0.618, out.width = "80%")
```

```{r load-data, include=FALSE}
weekly_ae_activity_20231008 <- read_csv("data/weekly_ae_activity_20231008.csv")
HBT_area_names_and_population <- read_csv("data/HBT area names and population.csv")
Treatement_Location_names <- read_csv("data/Treatement Location names.csv")

tidy.data <- weekly_ae_activity_20231008 %>%
  select(-Country, -DepartmentType) %>%
  mutate(WeekEndingDate = ymd(WeekEndingDate)) %>%
  mutate(PercentageOver4HoursEpisode = 
           round((NumberOver4HoursEpisode/NumberOfAttendancesEpisode)*100, digits = 1))

data.HBT.pop <- left_join(tidy.data, HBT_area_names_and_population, by ="HBT")

data.TLnames <- Treatement_Location_names%>%
  rename("TreatmentLocation" = "Postcode of Treatment Location")%>%
  left_join(data.HBT.pop, Treatement_Location_names, by ="TreatmentLocation")

col_order <- c("WeekEndingDate", "HBT", "Area name", "Population", "TreatmentLocation",
               "Name of Treatement Location", "NumberOfAttendancesEpisode", "NumberWithin4HoursEpisode",
               "PercentageWithin4HoursEpisode", "NumberOver4HoursEpisode", "PercentageOver4HoursEpisode", 
               "NumberOver8HoursEpisode", "PercentageOver8HoursEpisode", "NumberOver12HoursEpisode", "PercentageOver12HoursEpisode")

data.order <- data.TLnames[, col_order]

data <- data.order %>%
  rename("Week_Ending_Date" = "WeekEndingDate",
         "Health_Board_Area_Code" = "HBT", 
         "Health_Board_Area_Name" = "Area name", 
         "Area_Population" = "Population", 
         "Treatment_Location_Code" = "TreatmentLocation", 
         "Treatment_Location_Name" = "Name of Treatement Location",
         "Total_Attendees" = "NumberOfAttendancesEpisode", 
         "Attendees_within_4hrs" = "NumberWithin4HoursEpisode", 
         "%_within_4hr" = "PercentageWithin4HoursEpisode", 
         "Attendees_Over_4hrs" = "NumberOver4HoursEpisode",
         "%_Over_4hr" = "PercentageOver4HoursEpisode",
         "Attendees_Over_8hrs" = "NumberOver8HoursEpisode",
         "%_Over_8hr" = "PercentageOver8HoursEpisode", 
         "Attendees_Over_12hrs" = "NumberOver12HoursEpisode",
         "%_Over_12hr" = "PercentageOver12HoursEpisode")
```


```{r include=FALSE}
style_xaringan(
  title_slide_background_image = "img/edinburgh-castle.jpg"
)
```

---
# our data/ how we tidied it etc/ where we got it, all that jazz

---

```{r Information on Scotland Data, include=FALSE}
data_table_1 <- data %>%
  group_by(Health_Board_Area_Name, Area_Population) %>%
  summarise(mean_attendances = round(mean(Total_Attendees), digits = 2)) %>%
  arrange(desc(mean_attendances))

```

```{r Scotland Information, echo = FALSE, out.width="50%", fig.height=3}
kable(head(data_table_1, n = 14), format = "html")
```
---
